name: Portfolio
url: https://curious-yu.github.io/simple-portfolio/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

timezone: America/Los_Angeles

excerpt_separator: "<!-- more -->"

collections:
